name: laravel-integrations-adapters

services:
  devtools:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    init: true
    stop_grace_period: 1s
    tty: true
    stdin_open: true
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: /bin/bash
